services:
  spy:
    image: ghcr.io/wormhole-foundation/guardiand:latest
    platform: linux/amd64
    ports:
      - 7073:7073
    entrypoint: bash -c "
      /guardiand \
      spy \
      --nodeKey /node.key \
      --spyRPC '[::]:7073' \
      --network ${WORMHOLE_NETWORK} \
      --bootstrap ${SPY_BOOTSTRAP}
      "
  redis:
    image: redis
    ports:
      - 6379:6379
  relayer:
    build: .
    command: npm run start
    environment:
      - ENVIRONMENT
      - ETH_EMITTER_ADDRESS
      - ETH_CHAIN
      - ETH_ISM_ADDRESS
      - ETH_NETWORK_URL
      - ETH_SIGNER
      - COSMOS_ISM_ADDRESS
      - COSMOS_CHAIN
      - COSMOS_EMITTER_ADDRESS
      - COSMOS_NETWORK_URL
      - COSMOS_HRP
      - COSMOS_GAS_PRICE
      - COSMOS_SIGNER
